//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIENSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class account
    {
        [Required(ErrorMessage = "Nhập tài khoản")]
        public string accountname { get; set; }
        [Required(ErrorMessage = "Nhập mật khẩu")]
        public string passwords { get; set; }
        public int id { get; set; }
        public Nullable<int> levels { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Monney Monney { get; set; }
    }
}
