
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIENSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class book
    {
        public int id { get; set; }
        public int idbook { get; set; }
        public string booktitle { get; set; }
        public string authorname { get; set; }
        [DisplayName("Upload File")]
        public string img { get; set; }
        [DisplayName("Upload File")]
        public string DataContent { get; set; }
        public Nullable<int> price { get; set; }

        public virtual booktopic booktopic { get; set; }

        public HttpPostedFileBase imgfile { get; set; }
        public HttpPostedFileBase datafile { get; set; }
    }
}


