//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIENSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class booktopic
    {
        [Required(ErrorMessage = "Vui Lòng nhập ID")]
        public int id { get; set; }
        [Required(ErrorMessage = "Vui Lòng nhập tên Chủ Đề")]
        public string nametopic { get; set; }
    
        public virtual book book { get; set; }
    }
}
