
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace THUVIENSO.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Customer_requirements
{

    public Nullable<int> id { get; set; }

    public int id1 { get; set; }

    public Nullable<int> Request { get; set; }

    public Nullable<int> statuss { get; set; }

    public Nullable<System.DateTime> dateyc { get; set; }

    public Nullable<System.DateTime> dateht { get; set; }



    public virtual customer customer { get; set; }

}

}
