
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace THUVIENSO.Models
{

using System;
    using System.Collections.Generic;
    
public partial class customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public customer()
    {

        this.Customer_requirements = new HashSet<Customer_requirements>();

    }


    public int id { get; set; }

    public string username { get; set; }

    public string addres { get; set; }

    public string phonenumber { get; set; }

    public string sex { get; set; }

    public Nullable<int> sodutk { get; set; }



    public virtual account account { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Customer_requirements> Customer_requirements { get; set; }

}

}
