//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIENSO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THUVIENSOEntities : DbContext
    {
        public THUVIENSOEntities()
            : base("name=THUVIENSOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<booktopic> booktopics { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Monney> Monneys { get; set; }
        public virtual DbSet<book> books { get; set; }
    }
}
