//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THUVIENSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monney
    {
        public int id { get; set; }
        public Nullable<int> monney1 { get; set; }
    
        public virtual account account { get; set; }
    }
}
